const BaseTemplate = require('./BaseTemplate');

class CustomTemplate extends BaseTemplate {
  async createStructure() {
    this.emitProgress('Creating Custom Project structure');

    await this.createFile(this.projectPath, 'package.json', JSON.stringify({
      name: `${this.projectName.toLowerCase().replace(/\s+/g, '-')}-custom`,
      version: "1.0.0",
      description: this.description || "A custom DevPilot project",
      scripts: {
        "start": "echo \"Error: no start script specified\" && exit 1"
      }
    }, null, 2));

    await this.generateRootGitignore();
    await this.generateRootReadme(`# ${this.projectName}\n\nCustom Project.\n\nThis is a minimal flexible project structure generated by DevPilot.\n`);
  }
}

module.exports = CustomTemplate;
